'use client'
import {Suspense,useRef,useState,useEffect,Component,type ReactNode} from 'react'
import {Canvas,useThree} from '@react-three/fiber'
import * as T from 'three'
import {RoomEnvironment} from 'three/examples/jsm/environments/RoomEnvironment.js'
import StreetEnvironment from './StreetEnvironment'
import DriveController,{type DriveState} from './DriveController'
import StreetMetrics,{event,type StreetSample} from './StreetMetrics'
import HeroCar from '../vehicle/HeroCar'
import ImprovedCockpit from '../cockpit-lab/ImprovedCockpit'
import {CockpitProvider,RADIO_PRESETS} from '../vehicle/CockpitContext'
import {useCruiseAudio} from '../audio/useCruiseAudio'
import {HERO_X} from '@/lib/cruise/constants'
import type {CruiseRuntime,CruiseVehicleId,CruiseTimeOfDay} from '@/lib/cruise/types'
import './master.css'
const businesses={buena:{name:'Buena Onda Record Store',description:'Vinyl discoveries, independent music and coastal listening sessions.',station:84},branches:{name:'Branches Vintage',description:'Vintage clothing and carefully collected pieces from another era.',station:144},billboard:{name:'Vice Nights',description:'A fictional coastal music event. Demonstration sponsorship.',station:34}}
type Business=keyof typeof businesses
class Guard extends Component<{children:ReactNode},{failed:boolean}>{state={failed:false};static getDerivedStateFromError(){return {failed:true}}render(){return this.state.failed?<p role="alert">The 3D scene could not load. <a href="/cruise">Return to Cruise</a>.</p>:this.props.children}}
function Lighting({time,high}:{time:CruiseTimeOfDay;high:boolean}){
 const {gl,scene}=useThree()
 useEffect(()=>{scene.environmentIntensity=time==='night'?.12:1},[scene,time])
 useEffect(()=>{const p=new T.PMREMGenerator(gl),r=new RoomEnvironment(),e=p.fromScene(r,.06);scene.environment=e.texture;return()=>{scene.environment=null;e.dispose();r.dispose();p.dispose()}},[gl,scene])
 return <><color attach="background" args={[time==='night'?'#182d45':time==='sunset'?'#bdd5d8':'#a8d8ec']}/><fog attach="fog" args={[time==='night'?'#182d45':'#bfd4d5',140,330]}/><hemisphereLight args={[time==='night'?'#8ea7d8':'#d1e9f5','#775b4e',time==='night'?.22:1.0]}/><directionalLight position={[-25,45,15]} color={time==='sunset'?'#ffd5a0':'#fff0d9'} intensity={time==='night'?.12:2.2} castShadow={high} shadow-mapSize={[2048,2048]} shadow-camera-left={-45} shadow-camera-right={45} shadow-camera-top={120} shadow-camera-bottom={-120} shadow-camera-far={300} shadow-normalBias={.03} /></>
}
export default function MiamiStreet(){
 const drive=useRef<DriveState>({distance:0,speed:3.5,lateral:2,steer:0,paused:true,glance:0}),runtime=useRef<CruiseRuntime>({distance:0,time:0,speed:0}),car=useRef<T.Group|null>(null)
 const [mode,setMode]=useState<'chase'|'driver'>('chase'),[vehicle,setVehicle]=useState<CruiseVehicleId>('island-trail'),[time,setTime]=useState<CruiseTimeOfDay>('sunset'),[high,setHigh]=useState(false),[ready,setReady]=useState(false),[running,setRunning]=useState(false),[radio,setRadio]=useState(false),[directory,setDirectory]=useState(false),[detail,setDetail]=useState<Business|null>(null),[nearby,setNearby]=useState<Business|null>(null),[stats,setStats]=useState<StreetSample|null>(null),[visible,setVisible]=useState(true)
 const dismissed=useRef(new Set<string>()),appeared=useRef(new Set<string>()),audio=useCruiseAudio()
 useEffect(()=>{if(!detail)return;const keys=(e:KeyboardEvent)=>{if(e.key==='Escape'){e.preventDefault();setDetail(null)}if(e.key==='Tab'){e.preventDefault();document.querySelector<HTMLButtonElement>('.mm-modal button')?.focus()}};document.addEventListener('keydown',keys);return()=>document.removeEventListener('keydown',keys)},[detail])
 useEffect(()=>{const handle=()=>{setVisible(!document.hidden);if(document.hidden){drive.current.paused=true;setRunning(false)}};document.addEventListener('visibilitychange',handle);return()=>document.removeEventListener('visibilitychange',handle)},[])
 function sample(s:StreetSample){setStats(s);setRunning(!drive.current.paused);const id=(Object.keys(businesses) as Business[]).find(id=>{const delta=businesses[id].station-s.distance;return delta>3&&delta<40&&!dismissed.current.has(id)});setNearby(id||null);if(id&&!appeared.current.has(id)){appeared.current.add(id);event('card-appearance',id)}}
 function explore(id:string){if(!(id in businesses))return;drive.current.paused=true;setRunning(false);setDetail(id as Business);event('explore',id)}
 function toggleDrive(){if(detail)return;if(drive.current.distance>=210)reset();drive.current.paused=!drive.current.paused;setRunning(!drive.current.paused)}
 function reset(){Object.assign(drive.current,{distance:0,lateral:2,speed:3.5,paused:true,steer:0});setRunning(false);dismissed.current.clear();appeared.current.clear();window.__streetSamples=[];event('restart','street')}
 const touch=(key:'steer'|'glance',value:number)=>({onPointerDown:(e:React.PointerEvent<HTMLButtonElement>)=>{e.currentTarget.setPointerCapture(e.pointerId);drive.current[key]=value},onPointerUp:()=>{drive.current[key]=0},onPointerCancel:()=>{drive.current[key]=0},onLostPointerCapture:()=>{drive.current[key]=0}})
 return <main className="miami-master" data-ready={ready}><header><div><small>BUENA ONDA / PLAYABLE STREET STUDY</small><h1>Ocean Drive, 1986.</h1></div><a href="/cruise">Original Cruise</a></header>
 <div className="mm-tools"><button onClick={toggleDrive} disabled={!ready}>{running?'Pause cruise':'Start cruise'}</button><button onClick={()=>setMode(mode==='chase'?'driver':'chase')}>{mode==='chase'?'Cockpit view':'Chase view'}</button><button onClick={()=>setRadio(!radio)}>Radio</button><button onClick={()=>setDirectory(!directory)}>Directory</button><button onClick={reset}>Restart</button><select aria-label="Vehicle" value={vehicle} onChange={e=>{setReady(false);setVehicle(e.target.value as CruiseVehicleId)}}><option value="island-trail">Island Trail</option><option value="classic-coupe">1967 classic coupe</option><option value="coastal-coupe">Coastal coupe</option></select><select aria-label="Time of day" value={time} onChange={e=>setTime(e.target.value as CruiseTimeOfDay)}><option>day</option><option>sunset</option><option>night</option></select><select aria-label="Quality" value={high?'desktop':'mobile'} onChange={e=>setHigh(e.target.value==='desktop')}><option value="mobile">Mobile quality</option><option value="desktop">Desktop shadows</option></select></div>
 <section className="mm-stage" aria-label="Playable Miami street"><Guard><CockpitProvider audio={audio} vehicleId={vehicle} autoLights={time==='night'} instant radioFocused focusRadio={()=>setRadio(true)}><Canvas dpr={high?[1,1.5]:1} shadows={high} frameloop={visible?'always':'never'} camera={{position:[2,3,7],fov:65,near:.04,far:350}} gl={{antialias:true,powerPreference:'high-performance',toneMapping:T.ACESFilmicToneMapping,toneMappingExposure:1}}><Lighting time={time} high={high}/><Suspense fallback={null}><StreetEnvironment timeOfDay={time} onAdClick={explore}/><group ref={car}><mesh rotation-x={-Math.PI/2} position={[0,.031,0]} scale={[1.05,2.25,1]}><circleGeometry args={[1,32]}/><meshBasicMaterial color="#172329" transparent opacity={.24} depthWrite={false}/></mesh><group position={[-HERO_X,0,0]}>{vehicle==='island-trail'?<ImprovedCockpit improved parked={false} runtime={runtime} camera={mode} quality={high?'high':'low'} timeOfDay={time} onReady={()=>setReady(true)}/>:<HeroCar vehicleId={vehicle} runtime={runtime} camera={mode} quality={high?'high':'low'} timeOfDay={time} weather="clear" onReady={()=>setReady(true)}/>}</group></group><DriveController state={drive} runtime={runtime} vehicle={car} cameraMode={mode} vehicleId={vehicle} onFinish={()=>setRunning(false)}/><StreetMetrics drive={drive} mode={mode} onSample={sample}/></Suspense></Canvas></CockpitProvider></Guard><div className="mm-status">{ready?`${mode==='driver'?'COCKPIT':'CHASE'} / ${stats?Math.round(stats.speed*3.6):13} km/h`:'Loading street…'}<span>{stats?`${stats.fps.toFixed(0)} FPS · ${Math.round(stats.distance)} / 210 m`:''}</span></div></section>
 <div className="mm-bottom"><div className="mm-touch"><button aria-label="Steer left" {...touch('steer',-1)}>←</button><button aria-label="Steer right" {...touch('steer',1)}>→</button><button {...touch('glance',1)}>Glance left</button><button {...touch('glance',-1)}>Glance right</button><label>Speed <input aria-label="Cruising speed" type="range" min="2" max="8" step=".5" defaultValue="3.5" onChange={e=>{drive.current.speed=Number(e.target.value)}}/></label></div><p>Arrows / WASD steer and change speed · Space pauses · 220 m local study · All sponsorships are demos.</p></div>
 {nearby&&!detail&&<aside className="mm-discovery" aria-label="Nearby business"><small>DEMO SPONSOR · NEARBY</small><strong>{businesses[nearby].name}</strong><p>{businesses[nearby].description}</p><button onClick={()=>explore(nearby)}>Explore</button><button aria-label="Dismiss discovery" onClick={()=>{dismissed.current.add(nearby);event('card-dismissal',nearby);setNearby(null)}}>Dismiss</button></aside>}
 {radio&&<section className="mm-radio" aria-label="Radio controls"><strong>{audio.station.name}</strong><span role="status">{audio.error||(audio.loading?'Connecting…':audio.playing?'Playing':audio.trackTitle||'Ready — tap Play')}</span><button onClick={audio.toggle}>{audio.playing?'Pause radio':'Play radio'}</button>{RADIO_PRESETS.map(s=><button key={s.id} aria-pressed={audio.stationId===s.id} onClick={()=>audio.selectStation(s.id)}>{s.name}</button>)}<label>Volume <input aria-label="Radio volume" type="range" min="0" max="1" step=".05" value={audio.volume} onChange={e=>audio.setVolume(Number(e.target.value))}/></label></section>}
 {directory&&<section className="mm-directory" aria-label="Business directory">{(Object.keys(businesses) as Business[]).map(id=><button key={id} onClick={()=>explore(id)}>{businesses[id].name}</button>)}</section>}
 {detail&&<div className="mm-backdrop"><div className="mm-modal" onKeyDown={e=>{if(e.key==="Escape"){e.preventDefault();setDetail(null)}if(e.key==="Tab")e.preventDefault()}} role="dialog" aria-modal="true" aria-label={businesses[detail].name}><small>DEMONSTRATION SPONSORSHIP</small><h2>{businesses[detail].name}</h2><p>{businesses[detail].description}</p><p>Cruising is paused. Your radio continues independently.</p><button autoFocus onClick={()=>setDetail(null)}>Back to street</button></div></div>}
 <p className="mm-credits">Coastal Coupe: Mazda RX-7 by IvOfficial, <a href="https://poly.pizza/m/SnIoWlh7S2">Poly Pizza</a>, <a href="https://creativecommons.org/licenses/by/3.0/">CC BY 3.0</a>, modified with an original cockpit. GTO: thecali, CC0. Palm: Yughues / Nobiax, CC0. Asphalt: Dimitrios Savva / Poly Haven, CC0.</p></main>
}
